version: '2'
services:
  speedtest:
    user: '501:20'
    container_name: speedtest
    image: opengg/speedtest
    ports:
      - 8989:8989
    volumes:
      - ./settings.toml:/settings.toml
      - ./speedtest.db:/speedtest.db
